#PBS -S /bin/bash
### General Options ###
#PBS -N P4-MD_pristine
#PBS -V
### Resource Handling ###
#PBS -l nodes=1:ppn=32
#PBS -q bahonar
#PBS -l walltime=100:00:00
### Output Stream Options ### 
### Mail Options ### 
#PBS -m bea
 
### Bash script ###
cd /home/99425001/Desktop/zabihi/pristine
source /home/99425001/cp2k-v7/cp2k-7.1.0/tools/toolchain/install/setup
mpirun -np 32 /home/99425001/cp2k-v7/cp2k/exe/local/cp2k.popt -i MD_p4-1_1050.restart -o out-P4-pristine-md.log 


exit 0